[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.49"
glutin = "0.32"
raw-window-handle = "0.6"
winit = { version = "0.30.0", default-features = false, features = ["rwh_06"] }
anyhow = "1.0.75"
